INT = "int"
DEC = "dec"
plus = "plus"
minus = "minus"
ID = "identifier"
KW = "keyword"
EQ = "assignvalue"
mul = "multiply"
div = "divide"

true = "true"
false = "false"
boolean = "boolean"

POWER = "POWER"
MOD = "modulo"
RPN = "right_parenthese"
LPN = "left_parenthese"

EE = "equal"
NE = "notequal"
LT = "less_than"
LTE = "less_than_or_equal_to"
GT = "greater_than"
GTE = "greater_than_or_equal_to"

END = "end"
